In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

In [2]:
products_data=pd.read_csv('balancedDATA.csv')
products_data

,NameDescription,categories
0,surco a conversion bar bike rack featuresused ...,Automotive
1,kent marine turbo calcium ounce bottle turbo ...,Pet Supplies
2,inch pro style swim snorkel breathe underwater...,Sports & Outdoors
3,zia natural skincare seaweed lift serum ounce ...,Beauty
4,nexcare waterproof bandage knee amp elbow ct ...,Health & Personal Care
...,...,...
35761,palladio rice paper natural unique tissue made...,"Arts, Crafts & Sewing"
35762,learning resource tool set piece molded plasti...,Toys & Games
35763,serious skin care aeye xr nanoencapsulated eye...,Beauty
35764,wireless phone xcessories travel charger samsu...,Cell Phones & Accessories
35765,fsgt g ch gun transmitter radio controlled car...,Toys & Games

# Rendre label numerique

In [3]:
l=[]
for text in products_data["categories"].unique():
    l.append(text)

y=[]
for text in products_data["categories"]:
    for j in range(18):
        if text==l[j]:
            y.append(j)
    
y = np.asarray(y)

yy = pd.Series(y)
yy

0        0
1        1
2        2
3        3
4        4
        ..
35761    5
35762    7
35763    3
35764    6
35765    7
Length: 35766, dtype: int64

# Extracting Features From TextData using TF-IDF

In [4]:
from sklearn import feature_extraction, model_selection, naive_bayes, pipeline, manifold, preprocessing

In [5]:
Text=[]
for text in products_data["NameDescription"]:
    Text.append(text)

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
# First, we need a vectorizer object
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(Text).toarray()
xx=  pd.DataFrame(x)
xx

,0,1,2,3,4,5,6,7,8,9,...,99060,99061,99062,99063,99064,99065,99066,99067,99068,99069
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35761,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35763,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35764,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35765,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

After feature extraction from our text it gives 117197 features.

# Linear Support Vector Classification

In [7]:
from sklearn.model_selection import train_test_split
# Split data into testing and training data
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1,test_size=0.2)

In [8]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import Conv1D, GlobalMaxPooling1D

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score

# Test of 4 models
models = [
    RandomForestClassifier(n_estimators=200, max_depth=3, random_state=0),
    LinearSVC(),
    MultinomialNB(),
    LogisticRegression(random_state=0),
]
CV = 5
cv_df = pd.DataFrame(index=range(CV * len(models)))
entries = []
for model in models:
    model_name = model.__class__.__name__
    print(model_name)
    accuracies = cross_val_score(model, x, y, scoring='accuracy', cv=CV)
    for fold_idx, accuracy in enumerate(accuracies):
        entries.append((model_name, fold_idx, accuracy))
print('model_name')
cv_df = pd.DataFrame(entries, columns=['model_name', 'fold_idx', 'accuracy'])

RandomForestClassifier
LinearSVC
MultinomialNB
LogisticRegression
model_name

In [10]:
cv_df.groupby('model_name').accuracy.mean()

model_name
LinearSVC                 0.871610
LogisticRegression        0.850920
MultinomialNB             0.830845
RandomForestClassifier    0.583683
Name: accuracy, dtype: float64

In [11]:
# test of Linear svc only

In [12]:
linear_svc = LinearSVC()
classifier = linear_svc.fit(x_train,y_train)

In [13]:
y_pred = classifier.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score
print("Number of features is", x_train.shape[1])
print("Test set accuracy of SVC Classifier is {}".format(round(accuracy_score(y_pred,y_test)*100,2)))

Number of features is 99070
Test set accuracy of MLPClassifier Classifier is 87.31

In [15]:
import pickle
pickle.dump(classifier, open('svc87.pkl', 'wb'))

In [16]:
loaded_model = pickle.load(open('svc87.pkl', 'rb'))
result = loaded_model.score(x_test, y_test)
print(result)

0.8730779983226167